# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

import numpy as np

# Let's define a one-dimensional array 

list_1 = [20,30,40,50,60,80,100,200,300,500,600]
list_1

[20, 30, 40, 50, 60, 80, 100, 200, 300, 500, 600]

In [2]:
# Let's create a numpy array from the list "my_list"
np_array = np.array(list_1)
np_array

array([ 20,  30,  40,  50,  60,  80, 100, 200, 300, 500, 600])

In [3]:
type(np_array)

numpy.ndarray

In [4]:
# Multi-dimensional (Matrix definition) 
md_array = np.array([ [2,4,6], [1,3,5] ])
md_array

array([[2, 4, 6],
       [1, 3, 5]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [5]:
 x = np.array([ [3,7,9,3], [4,3,2,2] ])
x

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [6]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(20)
x

array([0.81248303, 0.19469715, 0.41119338, 0.73972225, 0.69190094,
       0.6894148 , 0.70697066, 0.27559382, 0.5024894 , 0.06215011,
       0.31911296, 0.43210718, 0.61615519, 0.93706611, 0.40143477,
       0.09917885, 0.98603207, 0.0814482 , 0.32048842, 0.61630198])

In [7]:
# you can create a matrix of random number as well
x = np.random.rand(3,3)
x

array([[0.77307665, 0.40170866, 0.92325108],
       [0.23396614, 0.13820172, 0.89715469],
       [0.28146557, 0.4224085 , 0.246581  ]])

In [8]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1,20)
x


8

In [9]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1,100,15)
x

array([18, 27, 26, 85, 92, 47, 98, 49, 31, 29, 10, 20, 65, 94, 83])

In [10]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1,50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [11]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [12]:
# Matrix of ones
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Array of zeros
x = np.zeros((4,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [14]:
x = int(input('Enter a positive number'))
y = np.random.randint(1,x,10)
y

Enter a positive number45


array([31,  9, 14, 14, 33, 33, 38, 24, 36, 30])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [15]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
y = np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Add 2 numpy arrays together
sum = x+y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
sqr = x**2
sqr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [19]:
sqrt = np.sqrt(sqr)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [20]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [21]:
x = np.array([5,7,20])
y = np.array([9,15,4])
z = np.sqrt(x**2 + y**2)
z

array([10.29563014, 16.55294536, 20.39607805])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [22]:
arr = np.array([1,1,2,3,4,5,6,7,8,11])
arr

array([ 1,  1,  2,  3,  4,  5,  6,  7,  8, 11])

In [23]:
# Access specific index from the numpy array
arr[9]

11

In [24]:
# Starting from the first index 0 up until and NOT including the last element
arr[0:4]

array([1, 1, 2, 3])

In [25]:
# Broadcasting, altering several values in a numpy array at once
arr[0:3] = 12
arr

array([12, 12, 12,  3,  4,  5,  6,  7,  8, 11])

In [26]:
# Let's define a two dimensional numpy array
mtx = np.random.randint(1,10,(3,3))
mtx

array([[5, 3, 7],
       [5, 2, 4],
       [9, 8, 2]])

In [27]:
# Get a row from a mtrix
mtx[2]

array([9, 8, 2])

In [28]:
# Get one element
mtx[1][2]

4

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [29]:
X = np.array([[2, 30, 20, -2 ,-4],
              [3, 4,  40, -3, -2],
              [-3, 4, -6, 90, 10],
              [25, 45, 34, 22, 12],
              [13, 24, 22, 32, 37]])
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [30]:
mtx = np.random.randint(1,20, (5,5))
mtx

array([[ 9, 13,  3,  9,  7],
       [ 5, 16, 16, 15,  7],
       [19, 15, 15, 14, 16],
       [ 5,  7, 16,  6, 10],
       [18, 13, 15, 18,  8]])

In [31]:
new_mtx = mtx[mtx > 6]
new_mtx

array([ 9, 13,  9,  7, 16, 16, 15,  7, 19, 15, 15, 14, 16,  7, 16, 10, 18,
       13, 15, 18,  8])

In [32]:
# Obtain odd elements only
new_odd = mtx[mtx % 2 != 0]
new_odd


array([ 9, 13,  3,  9,  7,  5, 15,  7, 19, 15, 15,  5,  7, 13, 15])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [33]:
X = np.array([[2, 30, 20, -2 ,-4],
              [3, 4,  40, -3, -2],
              [-3, 4, -6, 90, 10],
              [25, 45, 34, 22, 12],
              [13, 24, 22, 32, 37]])
X[X < 0] = 0
X[X %2 != 0] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [34]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [35]:
import pandas as pd

In [36]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
bank_client = pd.DataFrame({'Bank Client ID': [11,12,13,14,15],
                           'Client Name': ['Sam','Ram','Tim','Cook','Steve'],
                           'Net Worth ($)': [1200,3200,7800,1234, 9999],
                           'Year with Bank': [2,4,3,6,7]})
bank_client

Bank Client ID Client Name  Net Worth ($)  Year with Bank
0              11         Sam           1200               2
1              12         Ram           3200               4
2              13         Tim           7800               3
3              14        Cook           1234               6
4              15       Steve           9999               7

In [37]:
# Let's obtain the data type 
type(bank_client)

pandas.core.frame.DataFrame

In [38]:
# you can only view the first couple of rows using .head()
bank_client.head()

Bank Client ID Client Name  Net Worth ($)  Year with Bank
0              11         Sam           1200               2
1              12         Ram           3200               4
2              13         Tim           7800               3
3              14        Cook           1234               6
4              15       Steve           9999               7

In [39]:
# you can only view the last couple of rows using .tail()
bank_client.tail()

Bank Client ID Client Name  Net Worth ($)  Year with Bank
0              11         Sam           1200               2
1              12         Ram           3200               4
2              13         Tim           7800               3
3              14        Cook           1234               6
4              15       Steve           9999               7

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [40]:
portfolio_df = pd.DataFrame({'Stock Ticker Symbol': ['AAPL', 'AMZM', 'T', 'TCS'],
                            'Price per Share [$]': [231, 342, 123, 345],
                            'Number of Shares': [5, 12, 5,23]})
portfolio_df
Stocks_Value = portfolio_df['Price per Share [$]'] * portfolio_df['Number of Shares']
Stocks_Value.sum()

13809

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [41]:
!pip install lxml

# install this package as it helps in opening html files.

ERROR: Invalid requirement: '#install'


In [42]:
import ssl # resolve certificate errors

ssl._create_default_https_context = ssl._create_unverified_context

In [43]:
# Read tabular data using read_html
house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
house_price_df[0]

City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [44]:
retirement_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_df[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

# TASK #8: PANDAS OPERATIONS

In [45]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank Client ID': [11,12,13,14,15],
                           'Client Name': ['Sam','Ram','Tim','Cook','Steve'],
                           'Net Worth ($)': [1200,3200,7800,1234, 9999],
                           'Year with Bank': [6,8,3,4,7]})
bank_client_df

Bank Client ID Client Name  Net Worth ($)  Year with Bank
0              11         Sam           1200               6
1              12         Ram           3200               8
2              13         Tim           7800               3
3              14        Cook           1234               4
4              15       Steve           9999               7

In [46]:
# Pick certain rows that satisfy a certain criteria 
df_loyal = bank_client_df[ bank_client_df['Year with Bank']>= 5]
df_loyal

Bank Client ID Client Name  Net Worth ($)  Year with Bank
0              11         Sam           1200               6
1              12         Ram           3200               8
4              15       Steve           9999               7

In [47]:
# Delete a column from a DataFrame
del bank_client_df['Bank Client ID']
bank_client_df

Client Name  Net Worth ($)  Year with Bank
0         Sam           1200               6
1         Ram           3200               8
2         Tim           7800               3
3        Cook           1234               4
4       Steve           9999               7

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [48]:
df_high_networth = bank_client_df[ bank_client_df['Net Worth ($)']>= 5000]
df_high_networth

df_high_networth['Net Worth ($)'].sum()

17799

# TASK #9: PANDAS WITH FUNCTIONS

In [49]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [50]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def inc_networth(balance):
    return balance *1.2

In [51]:
# You can apply a function to the DataFrame 
bank_client_df['Net worth [$]'].apply(inc_networth)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [52]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [53]:
def inc_stock(balance):
    return balance * 3+200

In [54]:
results = bank_client_df['Net worth [$]'].apply(inc_stock)
results

0    10700
1    87200
2    30200
3     6200
Name: Net worth [$], dtype: int64

In [55]:
results.sum()

134300

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [56]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [79]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by = 'Years with bank')

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [80]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [82]:
# Set inplace = True to ensure that change has taken place in memory 
bank_client_df.sort_values(by = 'Years with bank', inplace = True)

In [83]:
# Note that now the change (ordering) took place 
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [61]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [87]:
df1 = pd.DataFrame({ 'A': ['A0', 'A1', 'A2','A3'],
                   'B': ['B0', 'B1','B2','B3'],
                   'C': ['C0', 'C1','C2','C3'],
                  'D': ['D0', 'D1','D2','D3'] }, index = [0,1,2,3])
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [89]:
df2 = pd.DataFrame({ 'A': ['A4', 'A5', 'A6','A7'],
                   'B': ['B4', 'B5','B6','B7'],
                   'C': ['C4', 'C5','C6','C7'],
                  'D': ['D4', 'D5','D6','D7'] }, index = [4,5,6,7])
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [91]:
pd.concat([df1,df2])

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [93]:
raw_data = { 'Bank Client ID' : ['1','2','3','4','5'],
           'First Name': ['Nancy', 'Ram', ' Shyam','Bob','Alam'],
           'Last Name': ['Rob','Kapoor','Mangal','Singh','George']}
Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1

Bank Client ID First Name Last Name
0              1      Nancy       Rob
1              2        Ram    Kapoor
2              3      Shyam    Mangal
3              4        Bob     Singh
4              5       Alam    George

In [94]:
raw_data = { 'Bank Client ID' : ['6','7','8','9','10'],
           'First Name': ['Ausk', 'Mr', ' SHaider','Tim','Cook'],
           'Last Name': ['Rob','Kapoor','Mangal','Singh','George']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2

Bank Client ID First Name Last Name
0              6       Ausk       Rob
1              7         Mr    Kapoor
2              8    SHaider    Mangal
3              9        Tim     Singh
4             10       Cook    George

In [96]:
raw_data = { 'Bank Client ID' : ['1','2','3','4','5','6','7','8','9','10'],
           'Annual Salary [$/year]' : [23000, 12000, 45000, 23000, 12389, 67000, 45673, 45367, 99000, 123000]}
bank_df_salary = pd.DataFrame(raw_data, columns=['Bank Client ID', 'Annual Salary [$/year]' ] )
bank_df_salary

Bank Client ID  Annual Salary [$/year]
0              1                   23000
1              2                   12000
2              3                   45000
3              4                   23000
4              5                   12389
5              6                   67000
6              7                   45673
7              8                   45367
8              9                   99000
9             10                  123000

In [102]:
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all

Bank Client ID First Name Last Name
0              1      Nancy       Rob
1              2        Ram    Kapoor
2              3      Shyam    Mangal
3              4        Bob     Singh
4              5       Alam    George
0              6       Ausk       Rob
1              7         Mr    Kapoor
2              8    SHaider    Mangal
3              9        Tim     Singh
4             10       Cook    George

In [103]:
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all

Bank Client ID First Name Last Name  Annual Salary [$/year]
0              1      Nancy       Rob                   23000
1              2        Ram    Kapoor                   12000
2              3      Shyam    Mangal                   45000
3              4        Bob     Singh                   23000
4              5       Alam    George                   12389
5              6       Ausk       Rob                   67000
6              7         Mr    Kapoor                   45673
7              8    SHaider    Mangal                   45367
8              9        Tim     Singh                   99000
9             10       Cook    George                  123000

In [ ]:
new_client = {'Bank Client ID': ['11'],
             'First Name': ['Ryan'],
             'Last Name': ['Ship'],
             'Annual Salary [$/year]': [7600]}
new_client_df = pd.DataFrame(new_client, columns=['Bank Client ID','First Name','Last Name','Annual Salary [$/year]'])
new_client_df

Bank Client ID First Name Last Name  Annual Salary [$/year]
0             11       Ryan      Ship                    7600

In [ ]:
new_df =pd.concat([bank_df_all,new_client_df])
new_df

Bank Client ID First Name Last Name  Annual Salary [$/year]
0              1      Nancy       Rob                   23000
1              2        Ram    Kapoor                   12000
2              3      Shyam    Mangal                   45000
3              4        Bob     Singh                   23000
4              5       Alam    George                   12389
5              6       Ausk       Rob                   67000
6              7         Mr    Kapoor                   45673
7              8    SHaider    Mangal                   45367
8              9        Tim     Singh                   99000
9             10       Cook    George                  123000
0             11       Ryan      Ship                    7600